name: Initialize the project from template

on: [push]

permissions: write-all

jobs:
  rename-project:
    if: ${{ !contains (github.repository, '/python-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_NAME_SNAKE_CASE=$(echo ${{ env.REPOSITORY_NAME }} | sed -e 's,-,_,')" >> $GITHUB_ENV
        shell: bash

      - name: Initialize the project
        run: |
          echo "Renaming the project to ${{ env.REPOSITORY_NAME }}"
          sed -i "" s/custom_module/${{ env.REPOSITORY_NAME_SNAKE_CASE }}/g docker-compose.yml
          sed -i "" s/custom_module/${{ env.REPOSITORY_NAME_SNAKE_CASE }})/g Makefile
          sed -i "" s/custom_module/${{ env.REPOSITORY_NAME_SNAKE_CASE }})/g setup.py
          sed -i "" s/custom_module/${{ env.REPOSITORY_NAME_SNAKE_CASE }})/g .github/formatting.yml
          sed -i "" s/custom_module/${{ env.REPOSITORY_NAME_SNAKE_CASE }})/g .github/linting.yml
          sed -i "" s/python-template/${{ env.REPOSITORY_NAME }}/g .lfsconfig
          sed -i "" s/python-template/${{ env.REPOSITORY_NAME }}/g README.md
          sed -i "" s/python-template/${{ env.REPOSITORY_NAME }}/g .devcontainer/devcontainer.json
          sed -i "" s/python-template/${{ env.REPOSITORY_NAME }}/g .devcontainer/docker-compose.devcontainer.yml
          mv custom_module ${{ env.REPOSITORY_NAME_SNAKE_CASE }})
          rm -f .github/initialize.yml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Initialized repository"
          push_options: --force
